- hosts: 127.0.0.1
  connection: local
  become: yes
  # ask-become-pass: yes

  roles:
    - main
    - laptop
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ lookup('env','USER') }}"
          visual_studio_code_extensions:
            - activecove.marquee
            - alefragnani.Bookmarks
            - aaron-bond.better-comments
            - bierner.markdown-mermaid
            - christian-kohler.path-intellisense
            - CoenraadS.bracket-pair-colorizer-2
            - dBizzy.dbizzy
            - damonsk.vscode-wardley-maps
            - DavidAnson.vscode-markdownlint
            - GitLab.gitlab-workflow
            - hediet.vscode-drawio
            - IBM.output-colorizer
            - kubescape.kubescape
            - jmmeessen.jenkins-declarative-support
            - janjoerke.jenkins-pipeline-linter-connector
            - lacroixdavid1.vscode-format-context-menu
            - lunuan.kubernetes-templates
            - mintlify.document
            - ms-azuretools.vscode-docker
            - ms-kubernetes-tools.vscode-kubernetes-tools
            - ms-vscode.cpptools
            - ms-python.python
            - ms-vscode-remote.remote-wsl
            - ms-vscode-remote.remote-containers
            - ms-vscode-remote.remote-ssh
            - MS-vsliveshare.vsliveshare
            - narsenico.vscode-progressive-increment
            - quicktype.quicktype
            - shd101wyy.markdown-preview-enhanced
            - streetsidesoftware.code-spell-checker
            - streetsidesoftware.code-spell-checker-spanish
            - tahabasri.snippets
            - tomoki1207.pdf
            - usernamehw.errorlens
            - vscodevim.vim
            - yzhang.markdown-all-in-one
            #- vscoss.vscode-ansible
            
