- hosts: all
  become: true
  roles:
    - main
    - server

# - hosts: nas
#   become: true
#   roles:
#    - dockstarter
# #    - nas
# #    - role: geerlingguy.nfs
# #      nfs_exports: [
# #        "/home/agredain/Downloads 192.168.1.129(rw,sync,no_subtree_check)"
# #      ]

