- hosts: all
  become: yes

  tasks:
  - name: Apt Update
    apt:
      update-cache: yes

  - name: List off upgradable packages
    command: apt list --upgradable
    register: upgradable_std

  - set_fact:
      upgradeable: "{{ upgradable_std.stdout_lines[1:] }}"

  - name: Show me
    debug:
      var: upgradeable

  - name: 
    pause:
      prompt: Please check the list. Press return to continue. Press Ctrl+c and then "a" to abort

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest

  - name: Update Dockstarter
    shell: ds -u

