---
# tasks file for barebone

# Other repositories
- name: Add Kodi Repository
  apt_repository:
    repo: ppa:team-xbmc/ppa
    state: present

- name: Update all packages to the latest version
  apt:
    upgrade: dist

# Extra packages
- name: Install Extras Packages
  apt:
    name:
    - x264
    - x265
    
# Extra packages
- name: Install Kodi Packages
  apt:
    name:
    - kodi
    - kodi-screensaver*
    - kodi-game-libretro*
    - kodi-inputstream-adaptive
    - kodi-inputstream-rtmp
    - kodi-peripheral-joystick
    - kodi-vfs-*
