---
# tasks file for main

# https://dev.to/uf4no/my-kubuntu-osx-look-alike-desktop-setup-219g
# https://nerdfonts.com/

# TODO: Autofirma
# https://www.opendesktop.org/p/1282623/
# Station
# Descargar e instalar MPLAB, ide de desarrollo de Microchip wget http://www.microchip.com/mplabx-ide-linux-installer -O /tmp/mplabx-ide-linux-installer.sh && sudo sh /tmp/mplabx-ide-linux-installer.sh -- --mode unattended
# Dropbox https://www.dropbox.com/install-linux
# https://freefilesync.org/
# https://forum.kde.org/viewtopic.php?f=66&t=82348
# qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'ShowDesktopGrid'
# https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md#bobthefish
# https://github.com/nicolargo/glances


# Other repositories
- name: Extra Repositories
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - ppa:atareao/atareao # Repositorio atareao/atareao, para varias aplicaciones: Touchpad-Indicator, Pomodoro Indicator, 2gi, My Weather Indicator. http://www.atareao.es/
    - ppa:peterlevi/ppa # Repositorio peterlevi, Variety, aplicación que cambia el fondo de escritorio de forma regular.
    - ppa:webupd8team/y-ppa-manager # Repositorio webupd8team, y-ppa-manager, herramienta para gestionar los PPAs.
    # - ppa:jd-team/jdownloader # Repositorio de jdownloader
    # - ppa:musicbrainz-developers/stable # Repositorio de musicbrainz picard
    - ppa:webupd8team/java # Repositorio de Oracle Java
    - ppa:rikmills/latte-dock # Dock para plasma
    - ppa:libreoffice/ppa # LibreOffice PPA
    - ppa:zeal-developers/ppa
    - ppa:oguzhaninan/stacer # Stacer PPA
    - ppa:nextcloud-devs/client

- name: Add Microsoft Extra fonts to all apps
  shell: fc-cache -f -v
 
#- name: Install Cheat.sh
#  shell: curl https://cht.sh/:cht.sh | sudo tee /usr/local/bin/cheat.sh && chmod +x/usr/local/bin/cheat.sh

- name: Update all packages to the latest version
  apt:
    upgrade: dist

# Extra packages
- name: Install Extras Packages
  apt:
    name: "{{ item }}"
  with_items:
    - ubuntu-restricted-extras
    - x264
    - x265
    - exfat-fuse 
    - exfat-utils
    - hplip
    - picard # Aplicación para análisis y reconocimiento de álbumnes de música
    - rar 
    - unrar
    - zip
    - unzip
    - calibre # Calibre, gestor y organizador de libros electrónicos, conversor de libros electrónicos e-book
    - gparted # GParted es un editor de particiones 
    - simple-scan
    - fslint # Installar FSlint (FileSystem Lint) para buscar y eliminar archivos duplicados
    - hardinfo # HardInfo, interfaz gráfica que muestra información del sistema, memoria, procesador, kernell, entre otras cosas
    - lm-sensors # lm-sensors, herramientas para leer la información de los sensores de temperatura, voltaje y ventiladores
    - microcode.ctl # Microcódigo en procesadores Intel
    - pdfmod # pdfmod, editor PDF, modificar documentos PDF, permitiéndote reordenar, girar, quitar, añadir, combinar documentos arrastrándolos..
    - pdfshuffler # PDF-Shuffler, aplicación gráfica interactiva e intuitiva que permite fusionar, dividir y volver a organizar las páginas de los documentos PDF
    - sysinfo # Sysinfo, herramienta gráfica para mostrar información sobre la configuración del hardware
    - vlc # VLC, reproductor multimedia archivos multimedia, así como DVD, protocolos Audio CD, VCD y streaming diversos..
    - browser-plugin-vlc 
    - libvlc5 
    # - libvlccore8
    - bleachbit # Installar Bleachbit, el Ccleaner de linux
    - filelight # Intallar Filelight, aplicación para ver el espacio ocupado por archivos y directorios de forma visual
    - variety # Variety, aplicación que cambia el fondo de escritorio de forma regular, el uso de imágenes especificadas por el usuario o descargados automáticamente.
    # - anki # Aplicación de tarjetas para reforzar la memoria
    - bleachbit # El Ccleaner de linux
    - latte-dock # Dock para Plasma supermolón
    # - jdownloader-installer # Jdownloader, gestor de descargas
    - ipython # Interprete de python
    - retext # Installar Retext para editar y visualizar markdown
    - krename
    - preload # Carga las aplicaciones mas rápidamente.
    - prelink # Se encarga de preenlazar las librerías que necesitan las aplicaciones que utilizamos, reduciendo así los tiempos de apertura
    - git
    - fish # Interprete de comandos supermolón
    - xbindkeys
    - zeal # Navegador de documentación para desarrolladores
    - kde-config-systemd # https://www.muylinux.com/2016/08/01/acelerar-apagado-systemd/
    - pinta # Paint equivalente
    - xserver-xorg-input-synaptics # Para hacer funcionar el Touchpad
    - bleachbit
    - ncdu # Estadísticas directorios por terminal
    - stacer # Software de Optimización y Monitoreo de Sistemas Linux
    - nextcloud-client
    
# Google Chrome
- name: Chrome repo key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present


- name: Chrome repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Install Chrome
  apt:
    name: google-chrome-stable

# Google Music Manager
- name: Google Music Manager repo key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- apt_repository:
    repo: deb [arch=amd64]  http://dl.google.com/linux/musicmanager/deb/ stable main
    state: present
    filename: google-musicmanager

- name: Install Google Music Manager
  apt:
    name: google-musicmanager-beta
    
# Insync
- name: Insync
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: ACCAF35C

- apt_repository:
    repo: deb http://apt.insync.io//ubuntu bionic non-free contrib
    state: present
    filename: insync

- name: Install Insync
  apt:
    name: insync
    
# Enpass
- name: Enpass repo keyserver
  apt_key: 
    url: https://dl.sinew.in/keys/enpass-linux.key
    state: present
   
- apt_repository:
    repo: deb http://repo.sinew.in/ stable main
    state: present
    filename: enpass

- name: Install Enpass
  apt:
    name: enpass
    
# Lutris
- name: Lutris repo keyserver
  apt_key: 
    url: https://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04/Release.key
    state: present
   
- apt_repository:
    repo: deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04/ ./
    state: present
    filename: lutris

- name: Install Lutris
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - lutris
    - steam
    
# Typora
- name: Typora repo key
  apt_key:
    url: https://typora.io/linux/public-key.asc
    state: present

- apt_repository:
    repo: deb https://typora.io/linux ./
    state: present

- name: Install Typora
  apt:
    name: typora
    
    
# Install "Rambox" snap
# - name: Install Rambox
#   snap:
#     name: rambox
#     state: present

# Install "GitKraken" snap
# - name: Install GitKraken
#   snap:
#     name: gitkraken
#     state: present

# Install "Mackup" snap
# - name: Install Mackup
#   snap:
#     name: mackup
#     state: present
#     classic

- name: Install and update Joplin
  shell: wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash

- name: Install Oh my Fish
  shell: curl -L https://get.oh-my.fish | fish
  # install https://github.com/abertsch/Menlo-for-Powerline/blob/master/Menlo%20for%20Powerline.ttf
  
  
# echo tmpfs /tmp tmpfs noatime,nodiratime,nodev,nosuid,mode=1777,defaults 0 0 >> /etc/fstab
# echo tmpfs /var/tmp tmpfs noatime,nodiratime,nodev,nosuid,mode=1777,defaults 0 0 >> /etc/fstab
