# Get Ferdi
- name: Get version list of Ferdi
  uri: 
    url: https://api.github.com/repos/getferdi/ferdi/releases/latest
    return_content: yes
    body_format: json
  register: ferdi

- name: Gather Ferdi version
  set_fact:
    ferdi_latest: "{{ ferdi.json.name }}"

- name: Install Ferdi
  apt:
    deb: "https://github.com/getferdi/ferdi/releases/download/v{{ ferdi_latest }}/ferdi_{{ ferdi_latest }}_amd64.deb"
