# Insync
- name: Get keyring file
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: ACCAF35C

- name: Add Insync repository to list of repositories
  apt_repository:
    repo: deb http://apt.insync.io/ubuntu {{ansible_lsb.codename}} non-free contrib
    state: present
    filename: insync

- name: Install Insync
  apt:
    name: insync