---
# tasks file for main

# https://dev.to/uf4no/my-kubuntu-osx-look-alike-desktop-setup-219g
# https://nerdfonts.com/

# TODO: Autofirma
# https://www.opendesktop.org/p/1282623/
# https://freefilesync.org/
# https://forum.kde.org/viewtopic.php?f=66&t=82348
# qdbus org.kde.kglobalaccel /component/kwin invokeShortcut 'ShowDesktopGrid'
# https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/Themes.md#bobthefish


# Other repositories
- name: Extra Repositories
  apt_repository:
    repo: "{{ item }}"
  loop  :
    - ppa:atareao/atareao               # Repositorio atareao/atareao, para varias aplicaciones: Touchpad-Indicator, Pomodoro Indicator, 2gi, My Weather Indicator. http://www.atareao.es/
    #- ppa:peterlevi/ppa                # Repositorio peterlevi, Variety, aplicación que cambia el fondo de escritorio de forma regular.
    - ppa:webupd8team/y-ppa-manager     # Repositorio webupd8team, y-ppa-manager, herramienta para gestionar los PPAs.
    # - ppa:jd-team/jdownloader         # Repositorio de jdownloader
    #- ppa:webupd8team/java             # Repositorio de Oracle Java
    - ppa:libreoffice/ppa               # LibreOffice PPA
    #- ppa:zeal-developers/ppa
    - ppa:nextcloud-devs/client
    - ppa:appimagelauncher-team/stable  # Latest stable version of AppImageLauncher.

- name: Add Microsoft Extra fonts to all apps
  shell: fc-cache -f -v
 
#- name: Install Cheat.sh
#  shell: curl https://cht.sh/:cht.sh | sudo tee /usr/local/bin/cheat.sh && chmod +x/usr/local/bin/cheat.sh

- name: Update all packages to the latest version
  apt:
    upgrade: dist

# Extra packages
- name: Install Extras Packages
  apt:
    name:
    - appimagelauncher              # Integrate AppImages to your application launcher with one click, and manage, update and remove them from there.
    # - anki # Aplicación de tarjetas para reforzar la memoria
    - bleachbit                     # Installar Bleachbit, el Ccleaner de linux
    - filelight                     # Intallar Filelight, aplicación para ver el espacio ocupado por archivos y directorios de forma visual
    #- fslint                       # Installar FSlint (FileSystem Lint) para buscar y eliminar archivos duplicados
    - gparted                       # GParted es un editor de particiones
    - hardinfo                      # HardInfo, interfaz gráfica que muestra información del sistema, memoria, procesador, kernell, entre otras cosas
    - hplip
    - krename
    - kde-config-systemd            # https://www.muylinux.com/2016/08/01/acelerar-apagado-systemd/
    - latte-dock                    # Dock para Plasma supermolón
    - libvlc5
    - meld
    - nextcloud-client
    - pdfmod                        # pdfmod, editor PDF, modificar documentos PDF, permitiéndote reordenar, girar, quitar, añadir, combinar documentos arrastrándolos..
    - picard                        # Aplicación para análisis y reconocimiento de álbumnes de música
    - pinta                         # Paint equivalente
    - stacer                        # Software de Optimización y Monitoreo de Sistemas Linux
    - simple-scan
    - variety                       # Variety, aplicación que cambia el fondo de escritorio de forma regular, el uso de imágenes especificadas por el usuario o descargados automáticamente.
    - wakeonlan
    - vlc                           # VLC, reproductor multimedia archivos multimedia, así como DVD, protocolos Audio CD, VCD y streaming diversos..
    - x264
    - x265
    - xbindkeys
    - xserver-xorg-input-synaptics  # Para hacer funcionar el Touchpad
    - zeal                          # Navegador de documentación para desarrolladores
    
- name: Install Snap packages
  snap:
    name:
    - gitkraken
    - joplin-desktop
    - breaktimer        # Pomodoro application
    - authy             # strong authentication
    classic: yes
    
- name: Install Brave
  include_tasks: brave.yml

- name: Install Enpass
  include_tasks: enpass.yml

- name: Install Typora
  include_tasks: typora.yml

- name: Install Ferdi
  include_tasks: ferdi.yml

- name: Install Httpi Desktop
  include_tasks: httpi.yml

- name: Install OpenLens Desktop
  include_tasks: openlens.yml

- name: Install Chezmoi
  include_tasks: chezmoi.yml

# - name: Install Insync
#   include_tasks: insync.yml
    
# Lutris
# - name: Lutris repo keyserver
#   apt_key: 
#     url: https://download.opensuse.org/repositories/home:/strycore/xUbuntu_{{ansible_lsb.release}}/Release.key
#     state: present
   
# - apt_repository:
#     repo: deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_{{ansible_lsb.release}}/ ./
#     state: present
#     filename: lutris

# - name: Install Lutris
#   apt:
#     name:
#     - lutris
#     - steam
    
# Install "Rambox" snap
# - name: Install Rambox
#   snap:
#     name: rambox
#     state: present

# Install "Mackup" snap
# - name: Install Mackup
#   snap:
#     name: mackup
#     state: present
#     classic

#- name: Install Oh my Fish
#  shell: curl -L https://get.oh-my.fish | fish
  # install https://github.com/abertsch/Menlo-for-Powerline/blob/master/Menlo%20for%20Powerline.ttf
  
  
# echo tmpfs /tmp tmpfs noatime,nodiratime,nodev,nosuid,mode=1777,defaults 0 0 >> /etc/fstab
# echo tmpfs /var/tmp tmpfs noatime,nodiratime,nodev,nosuid,mode=1777,defaults 0 0 >> /etc/fstab
- name: Download StarShip
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/install.sh

- name: Run StarShip
  shell: cat /tmp/install.sh | sh -s -- -y

#  https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/UbuntuMono.zip

# https://github.com/xxh/xxh
- name: Install xxh
  pip:
    name: xxh-xxh

- name: Install xxh plugin
  shell: "xxh +I {{ item }}" 
  loop: 
    - xxh-shell-bash
    - xxh-plugin-prerun-dotfiles
    - xxh-plugin-prerun-starship+git+https://github.com/izissise/xxh-plugin-prerun-starship.git

- name: Configure xxh
  blockinfile:
    path: ~/.config/xxh/config.xxhc
    block: |
      hosts:
        ".*":
          +s: bash
          +I: xxh-plugin-prerun-dotfiles

- name: Download Appimage Update Tool
  get_url:
    url: https://github.com/AppImage/AppImageUpdate/releases/download/2.0.0-alpha-1-20220124/appimageupdatetool-x86_64.AppImage
    dest: ~/Applications
    mode: 764

