---
# tasks file for server

- name: Update all packages to the latest version
  apt:
    upgrade: dist

# Extra packages
- name: Install Extras Packages
  apt:
    name:
    - cockpit
    - cockpit-docker
    - cockpit-networkmanager
    - cockpit-systemd
    - borgbackup
    