---
# tasks file for main

- name: Update all packages to the latest version
  apt:
    upgrade: dist

# Extra packages
- name: Install Extras Packages
  apt:
    name:
    - ubuntu-restricted-extras
    - exfat-fuse 
    - exfat-utils
    - rar 
    - unrar
    - zip
    - unzip
    - curl
    - neofetch      # Neofetch displays an ASCII logo of your Linux distribution along with information related to your system in the terminal
    - lm-sensors    # Herramientas para leer la información de los sensores de temperatura, voltaje y ventiladores
    - microcode.ctl # Microcódigo en procesadores Intel
    - rmlint        # Remove duplicate files by hash
    - preload       # Speed application load
    - prelink       # Se encarga de preenlazar las librerías que necesitan las aplicaciones que utilizamos, reduciendo así los tiempos de apertura
    - git
    - fish          # Interprete de comandos supermolón
    - ncdu          # Folder statistic in terminal
    - most          # Colorful manpages
    - bleachbit     # Remove unnecessary system files

# - name: Set Fish as default Interpreter
#   command: chsh -s 'which fish'

#- name: Make most permanent
  #blockinfile:
    #path: ~/.bashrc
    #line: |
      #export PAGER="most"
      #alias ls='ls --color=auto'
      #alias dir='dir --color=auto'
      #alias vdir='vdir --color=auto'
      #alias grep='grep --color=auto'
      #alias fgrep='fgrep --color=auto'
      #alias egrep='egrep --color=auto'
