---
# tasks file for main

- name: Update all packages to the latest version
  apt:
    upgrade: dist

# Extra packages
- name: Install Extras Packages
  apt:
    name:
    - ubuntu-restricted-extras
    - exfat-fuse 
    - exfat-utils
    - rar 
    - unrar
    - zip
    - unzip
    - curl
    - lm-sensors    # Herramientas para leer la información de los sensores de temperatura, voltaje y ventiladores
    - microcode.ctl # Microcódigo en procesadores Intel
    - rmlint        # Remove duplicate files by hash
    - preload       # Speed application load
    - prelink       # Se encarga de preenlazar las librerías que necesitan las aplicaciones que utilizamos, reduciendo así los tiempos de apertura
    - git
    - fish          # Interprete de comandos supermolón
    - ncdu          # Folder statistic in terminal
    - most          # Colorful manpages
    . bleachbit     # Remove unnecessary system files 

# - name: Set Fish as default Interpreter
#   command: chsh -s 'which fish'

- name: Make most permanent
  lineinfile:
    path: ~/.bashrc
    line: export PAGER="most"
