---
# tasks file for nas

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Add General Backup Daemon Files
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
    force: no
  loop:
  - media-backup.mount
  - media-backup.automount
  - backup-script.service

- name: Enable General Backup Daemon
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  loop:
  - media-backup.automount
  - backup-script.service
    
- name: Clean Agredain photos daily
  cron:
    name: "Clean Nextcloud photos"
    special_time: daily
    job: "/media/data/scripts/clean_photos.sh"