---
# tasks file for nas

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Add General Backup Daemon Files
  copy:
    src: backup-script.service
    dest: /etc/systemd/system/
    force: no

- name: Add General Backup Udev Files
  copy:
    src: 90-mount_media_backup.rules
    dest: /etc/udev/rules.d/
    force: no
  
- name: Clean Agredain photos daily
  cron:
    name: "Clean Nextcloud photos"
    special_time: daily
    job: "/media/data/scripts/clean_photos.sh"